
name: "cart"
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    env_file:
      - ./.env
    networks:
      - micro-network

networks:
  micro-network:
    external: true
    name: microservices-net
