version: "3.8"

services:
  upload-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3006:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/upload
    depends_on:
      - postgres
    networks:
      - upload-network

  postgres:
    image: postgres:15.4
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=upload
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - upload-network

networks:
  upload-network:
    driver: bridge

volumes:
  postgres-data:
