
name: "review"
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
    env_file:
      - ./.env
    networks:
      - micro-network

networks:
  micro-network:
    external: true
    name: microservices-net
